// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../commands.hpp"
#include "../views.hpp"

auto SOUND::COMMANDS::table() -> const Vector<SHELL::Command>& {
  static const Vector<SHELL::Command> table = [] {
    Vector<SHELL::Command> rows = {
      {"session", "",
       COMMANDS::document},
      {"new",
       ""
       "seated",
       COMMANDS::fresh},
      {"save", "", COMMANDS::save},
      {"open", "", COMMANDS::open},
      {"sessions", "", COMMANDS::saved},
      {"husks",
       ""
       "speak",
       COMMANDS::husks},
      {"time", "",
       COMMANDS::timing},
      {"play", "",
       COMMANDS::play},
      {"stop", "", COMMANDS::stop},
      {"locate", "", COMMANDS::locate},
      {"chase",
       ""
       "holds it, or sets the chase: chase on|off",
       COMMANDS::chase},
      {"settings",
       ""
       "settings own on|off, settings shade light|dark",
       COMMANDS::settings},
      {"tempo",
       ""
       "[at <pulses>] | tempo off at <pulses>",
       COMMANDS::tempo},
      {"metre",
       ""
       "[at <pulses>] | metre off at <pulses>",
       COMMANDS::metre},
      {"loop",
       ""
       "<text ...>, lists the loops, or turns the wrap: loop on|off",
       COMMANDS::cycle},
      {"unloop", "", COMMANDS::unloop},
      {"tag",
       "",
       COMMANDS::tag},
      {"untag", "", COMMANDS::untag},
      {"ends", "",
       COMMANDS::ends},
      {"ahead", "",
       COMMANDS::ahead},
      {"behind", "",
       COMMANDS::behind},
      {"scale",
       ""
       "[at <pulses>] | scale off [at <pulses>]",
       COMMANDS::scale},
      {"plugins", "", COMMANDS::offers},
      {"seat", "",
       COMMANDS::seat},
      {"surface",
       ""
       "surface <track> <input|output|midiout> <device ...>",
       COMMANDS::surface},
      {"io", "",
       COMMANDS::io},
      {"main",
       ""
       "device the clock stands on",
       COMMANDS::main},
      {"pair",
       ""
       "pair <node> <first lane>",
       COMMANDS::pair},
      {"root", "", COMMANDS::root},
      {"wire", "", COMMANDS::wire},
      {"unwire", "", COMMANDS::unwire},
      {"quiet",
       "",
       COMMANDS::quiet},
      {"bypass",
       ""
       "bypass <root> <out> [on|off]",
       COMMANDS::bypass},
      {"unseat", "",
       COMMANDS::unseat},
      {"home", "", COMMANDS::home},
      {"graph", "",
       COMMANDS::wiring},
      {"peak", "",
       COMMANDS::peak},
      {"note", "", COMMANDS::note},
      {"turn", "",
       COMMANDS::turn},
      {"bounce", "",
       COMMANDS::bounce},
      {"timeline", "",
       COMMANDS::tracks},
      {"track", "", COMMANDS::track},
      {"bus", "",
       COMMANDS::bus},
      {"name", "",
       COMMANDS::name},
      {"drop", "", COMMANDS::drop},
      {"lane", "", COMMANDS::lane},
      {"unlane", "",
       COMMANDS::unlane},
      {"kind",
       ""
       "<kind>",
       COMMANDS::kind},
      {"admit",
       ""
       "admit <track> <lane> [on|off]",
       COMMANDS::admit},
      {"clip", "", COMMANDS::place},
      {"span", "", COMMANDS::span},
      {"export",
       ""
       "and writes it as a wav: export <track> [path]",
       COMMANDS::exporting},
      {"join",
       ""
       "clip, the gaps empty",
       COMMANDS::join},
      {"lift", "", COMMANDS::lift},
      {"map",
       ""
       "map <track> <lane> [plugin|none]",
       COMMANDS::map},
      {"restore", "",
       COMMANDS::restore},
      {"stocks", "", COMMANDS::stocks},
      {"stock", "", COMMANDS::stock},
      {"author", "", COMMANDS::author},
      {"move", "",
       COMMANDS::move},
      {"stretch", "",
       COMMANDS::stretch},
      {"erase", "", COMMANDS::erase},
      {"take", "",
       COMMANDS::take},
      {"aim", "",
       COMMANDS::aim},
      {"plot", "",
       COMMANDS::plot},
      {"dial", "",
       COMMANDS::dial},
      {"sounding",
       ""
       "document's standing values",
       COMMANDS::sounding},
      {"history", "",
       COMMANDS::history},
      {"undo", "", COMMANDS::undo},
      {"redo", "", COMMANDS::redo},
      {"trim", "",
       COMMANDS::trim},
      {"roll", "",
       COMMANDS::roll},
      {"drive", "",
       COMMANDS::drive},
      {"strike", "",
       COMMANDS::strike},
      {"hear", "",
       COMMANDS::hear},
      {"record", "",
       COMMANDS::record},
      {"beat",
       ""
       "times: beat [n]",
       COMMANDS::beat},
      {"input",
       ""
       "one: input [<device> [<channel>]]",
       COMMANDS::input},
      {"views",
       "",
       COMMANDS::views},
      {"view", "",
       COMMANDS::view},
      {"panel", "", COMMANDS::panel},
      {"zoom", "",
       COMMANDS::zoom},
      {"pan", "",
       COMMANDS::pan},
      {"look", "",
       COMMANDS::look}};
    for (const VIEWS::View& unit : VIEWS::roster())
      rows.insert(rows.end(), unit.words.begin(), unit.words.end());
    return rows;
  }();
  return table;
}
